<?php

namespace App\Validators\Constraint;

use App\Validators\BirthdateValidator;
use Attribute;
use Symfony\Component\Validator\Constraint;

#[Attribute]
class Birthdate extends Constraint
{
    public $message = "si vous êtes effectivement né(e) le '{{ string }}', vous êtes trop jeune pour utiliser l'application";

    public function validatedBy(): string
    {
        return BirthdateValidator::class; // TODO: Change the autogenerated stub
    }
}