<?php

namespace App\Validators\Constraint;

use App\Validators\LevelValidator;
use Attribute;
use Symfony\Component\Validator\Constraint;

#[Attribute]
class Level extends Constraint
{
    public $message = 'le niveau "{{ string }} ne fait pas partie des niveaux disponibles';

    public function validatedBy(): string
    {
        return LevelValidator::class; // TODO: Change the autogenerated stub
    }
}